

pub enum OpCodes {
    InitMemory,
    NewValue,
    GetProperty,
    CallFunction,
    Mul,
    MovImm24,
    CallApply,
    Div,
    Or,
    Sub,
    PushArgs,
    LoadImm24,
    JumpFrame,
    NewFunction,
    LessThan,
    JumpIfFalse,
    SetProperty,
    Add,
    Jump,
    Halt,
    Shl,
    Ret,
    Equal,
    Xor,
    LoadDouble,
    Ushr,
    Shr,
    And,
    Mod,
    Lte,
    NotEqual,
    JumpIfTrue,
    TryCatch,
    StrictEqual,
    StrictNotEqual,
    Throw
}

impl OpCodes {
    pub fn as_str(&self) -> &'static str {
        match self {
            OpCodes::InitMemory => "INIT MEMORY",
            OpCodes::NewValue => "NEW VALUE",
            OpCodes::GetProperty => "GET PROPERTY",
            OpCodes::CallFunction => "CALL FUNCTION",
            OpCodes::Mul => "MUL",
            OpCodes::MovImm24 => "MOV Imm24",
            OpCodes::CallApply => "CALL APPLY",
            OpCodes::Div => "DIV",
            OpCodes::Or => "OR",
            OpCodes::Sub => "SUB",
            OpCodes::PushArgs => "PUSH ARGS",
            OpCodes::LoadImm24 => "LOAD IMM24",
            OpCodes::JumpFrame => "JUMP FRAME",
            OpCodes::NewFunction => "NEW FUNCTION",
            OpCodes::LessThan => "LESS THAN",
            OpCodes::JumpIfFalse => "JUMP IF FALSE",
            OpCodes::SetProperty => "SET PROPERTY",
            OpCodes::Add => "ADD",
            OpCodes::Jump => "JUMP",
            OpCodes::Halt => "HALT",
            OpCodes::Shl => "SHL",
            OpCodes::Ret => "RET",
            OpCodes::Equal => "EQUAL",
            OpCodes::Xor => "XOR",
            OpCodes::LoadDouble => "LOAD DOUBLE",
            OpCodes::Ushr => "USHR",
            OpCodes::Shr => "SHR",
            OpCodes::And => "AND",
            OpCodes::Mod => "MOD",
            OpCodes::Lte => "LTE",
            OpCodes::NotEqual => "NOT EQUAL",
            OpCodes::JumpIfTrue => "JUMP IF TRUE",
            OpCodes::TryCatch => "TRY CATCH",
            OpCodes::StrictEqual => "STRICT EQUAL",
            OpCodes::StrictNotEqual => "STRICT NOT EQUAL",
            OpCodes::Throw => "THROW"
        }
    }
}

